name: Build LaTeX document
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            resume_ru.tex
            resume_en.tex
            projects_ru.tex
            projects_en.tex
      - name: Upload
        run: |
          mkdir /tmp/pdf
          cp -f *.pdf /tmp/pdf
      - name: Publish builded content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          FOLDER: /tmp/pdf
          BRANCH: gh-pages
